version: '3'

###
# Demo Fin Server from deployed DockerHub container images
###
services:

  ###
  # Font End NodeJS Application Server
  ###
  server:
    image: ucdlib/fin-server:1.0.3
    env_file:
      - fin-example.env
    volumes:
      - ./conf:/etc/fin
    ports:
      - 3000:3001
    depends_on:
      - fcrepo
      - redis

  ###
  # Fedora Repository
  ###
  fcrepo:
    image: ucdlib/fin-fcrepo:v1.0.0
    env_file:
      - fin-example.env
    volumes:
      - fedora-data:/var/lib/jetty/fedora-data
    ports:
      - 8080:8080

  ###
  # Session, admin store
  ###
  redis:
    image: redis:3.2
    volumes:
      - redis-data:/data
    depends_on:
      - fcrepo  

  ###
  # UC DAMS Client UI
  ###
  ucd-lib-client:
    image: ucdlib/fin-ucd-lib-client:0.1.0
    env_file:
      - fin-example.env
    depends_on:
      - elasticsearch

  ###
  # Search
  ###
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - ./conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    depends_on:
      - server

  ###
  # Trusted Proxy for Services
  # required for loris service
  ###
  trustedproxy:
    image: ucdlib/fin-trusted-proxy:1.0.0
    env_file:
      - fin-example.env
    depends_on:
      - elasticsearch

  ###
  # IIIF Service
  ###
  loris:
    image: ucdlib/fin-loris-service:v0.0.2
    env_file:
      - fin-example.env
    depends_on:
      - server
      - trustedproxy
    volumes:
      - loris-data:/usr/local/share/images/loris

  ###
  # ES Indexer
  ###
  essync:
    image: ucdlib/fin-essync-service:0.1.0
    env_file:
      - fin-example.env
    depends_on:
      - server

  ###
  # Basic Username/Password AuthenticationService
  ###
  basic-auth:
    image: ucdlib/fin-basic-auth:0.0.1
    env_file:
      - fin-example.env
    depends_on:
      - server

###
# Docker data volumes
###
volumes:
  fedora-data:
    driver: local
  fedora-serialized-data:
    driver: local
  es-data:
    driver: local
  redis-data:
    driver: local
  loris-data:
    driver: local
