source:
  #host: 'https://sandbox.dams.library.ucdavis.edu'
  host: 'http://localhost:3001'
  #host: 'https://moments.dams.library.ucdavis.edu'
  base: /fcrepo/rest/moments
  collection: chardonnay
http:
  session: inf4
  ssl: tls1.2
  print: h
