host: https://sandbox.dams.library.ucdavis.edu
base: /fcrepo/rest/collection
collection: ex1-pets
transaction: true
metadata_foo: bar
metadata:
  is_metadata: ^(.*).ttl$
  file: FILE.ttl
http:
  session: inf4
  ssl: tls1.2
  print: hb
