source:
  host: 'https://sandbox.dams.library.ucdavis.edu'
  base: /fcrepo/rest
  collection: moments
contentTypes:
  jpg: image/jpeg
  yml: text/yaml
  jpeg: image/jpeg
  json: application/json
  png: image/png
  hdt: application/octet-stream
  err: application/octet-stream
